name: build docker images

# Controls when the workflow will run
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v4

      # Generate docker tags
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=develop,priority=900,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,enable=true,priority=600,prefix=pr-,suffix=,event=pr
            type=ref,event=tag
            type=ref,event=branch
            type=schedule

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request' && env.DOCKERHUB_USERNAME != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          # Multi-architecture build supporting all modern systems:
          # - linux/amd64: x86_64 (most PCs, servers, Intel/AMD)
          # - linux/i386: x86 32-bit (older PCs, legacy systems)
          # - linux/arm64: ARM64 (RPi4, RPi5, Apple Silicon, ARM servers)
          # - linux/arm/v7: ARMv7 (RPi3, RPi2, many ARM devices)
          # - linux/arm/v6: ARMv6 (RPi Zero, RPi1, older ARM devices)
          platforms: linux/amd64, linux/i386, linux/arm64, linux/arm/v7, linux/arm/v6
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
