name: Sync with Upstream

on:
  schedule:
    # Check for upstream changes every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual trigger

permissions:
  contents: write
  actions: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/dmunozv04/iSponsorBlockTV.git || true
          git fetch upstream

      - name: Check for changes
        id: changes
        run: |
          git fetch upstream main
          LOCAL=$(git rev-parse HEAD)
          REMOTE=$(git rev-parse upstream/main)
          if [ "$LOCAL" != "$REMOTE" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected from upstream"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes from upstream"
          fi

      - name: Merge upstream changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          echo "Attempting to merge upstream changes..."
          if git merge upstream/main --no-edit; then
            echo "Merge successful, preserving fork-specific files..."
            
            # Remove upstream workflows that don't apply to fork
            if [ -f ".github/workflows/update_docker_readme.yml" ]; then
              git rm .github/workflows/update_docker_readme.yml
              echo "Removed upstream DockerHub workflow"
            fi
            
            # Commit removal if files were deleted
            if ! git diff --cached --quiet; then
              git commit -m "Remove upstream workflows incompatible with fork (DockerHub credentials)"
            fi
            
            echo "Pushing changes..."
            git push origin main
            echo "sync_success=true" >> $GITHUB_OUTPUT
          else
            echo "Merge conflict detected! Manual intervention required."
            git merge --abort
            echo "sync_success=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        id: merge

      - name: Trigger build workflow
        if: steps.changes.outputs.changes == 'true' && steps.merge.outputs.sync_success == 'true'
        run: |
          echo "Triggering multi-arch Docker build..."
          gh workflow run build_docker_images.yml --repo ${{ github.repository }} --ref main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue on merge conflict
        if: steps.changes.outputs.changes == 'true' && steps.merge.outputs.sync_success == 'false'
        run: |
          gh issue create \
            --title "🚨 Upstream Sync Failed - Merge Conflict" \
            --body "The automated upstream sync failed due to merge conflicts. Manual intervention is required to resolve conflicts between your fork and the upstream repository. Please check the workflow logs and resolve conflicts manually." \
            --label "sync-conflict" \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}