name: Sync with Upstream

on:
  schedule:
    # Check for upstream changes every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual trigger

permissions:
  contents: write
  actions: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/dmunozv04/iSponsorBlockTV.git || true
          git fetch upstream

      - name: Check for changes
        id: changes
        run: |
          git fetch upstream main
          LOCAL=$(git rev-parse HEAD)
          REMOTE=$(git rev-parse upstream/main)
          if [ "$LOCAL" != "$REMOTE" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected from upstream"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes from upstream"
          fi

      - name: Merge upstream changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git merge upstream/main --no-edit
          git push origin main

      - name: Trigger build workflow
        if: steps.changes.outputs.changes == 'true'
        run: |
          gh workflow run build_docker_images.yml --ref main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}